@echo off
attrib +s .
attrib +s +h desktop.ini

attrib +s DirectXTK
attrib +s +h "DirectXTK\desktop.ini"

attrib +s "Icons"
attrib +s +h "Icons\desktop.ini"

attrib +s "Demo 0"
attrib +s +h "Demo 0\desktop.ini"
attrib +s "Demo 0\Code"
attrib +s "Demo 0\Release"
attrib +s "Demo 0\Debug"
attrib +s +h "Demo 0\Code\desktop.ini"
attrib +s +h "Demo 0\Release\desktop.ini"
attrib +s +h "Demo 0\Debug\desktop.ini"

attrib +s "Demo 1"
attrib +s +h "Demo 1\desktop.ini"
attrib +s "Demo 1\Code"
attrib +s "Demo 1\Release"
attrib +s "Demo 1\Debug"
attrib +s "Demo 1\Images"
attrib +s +h "Demo 1\Code\desktop.ini"
attrib +s +h "Demo 1\Release\desktop.ini"
attrib +s +h "Demo 1\Debug\desktop.ini"
attrib +s +h "Demo 1\Images\desktop.ini"

attrib +s "Demo 2"
attrib +s +h "Demo 2\desktop.ini"
attrib +s "Demo 2\Code"
attrib +s "Demo 2\Release"
attrib +s "Demo 2\Debug"
attrib +s "Demo 2\Images"
attrib +s +h "Demo 2\Code\desktop.ini"
attrib +s +h "Demo 2\Release\desktop.ini"
attrib +s +h "Demo 2\Debug\desktop.ini"
attrib +s +h "Demo 2\Images\desktop.ini"

attrib +s "Demo 3"
attrib +s +h "Demo 3\desktop.ini"
attrib +s "Demo 3\Code"
attrib +s "Demo 3\Release"
attrib +s "Demo 3\Debug"
attrib +s "Demo 3\Images"
attrib +s +h "Demo 3\Code\desktop.ini"
attrib +s +h "Demo 3\Release\desktop.ini"
attrib +s +h "Demo 3\Debug\desktop.ini"
attrib +s +h "Demo 3\Images\desktop.ini"

attrib +s "Demo 4"
attrib +s +h "Demo 4\desktop.ini"
attrib +s "Demo 4\Code"
attrib +s "Demo 4\Release"
attrib +s "Demo 4\Debug"
attrib +s "Demo 4\Images"
attrib +s +h "Demo 4\Code\desktop.ini"
attrib +s +h "Demo 4\Release\desktop.ini"
attrib +s +h "Demo 4\Debug\desktop.ini"
attrib +s +h "Demo 4\Images\desktop.ini"

attrib +s "Demo 5"
attrib +s +h "Demo 5\desktop.ini"
attrib +s "Demo 5\Code"
attrib +s "Demo 5\Release"
attrib +s "Demo 5\Debug"
attrib +s "Demo 5\Images"
attrib +s +h "Demo 5\Code\desktop.ini"
attrib +s +h "Demo 5\Release\desktop.ini"
attrib +s +h "Demo 5\Debug\desktop.ini"
attrib +s +h "Demo 5\Images\desktop.ini"

attrib +s "Demo 6"
attrib +s +h "Demo 6\desktop.ini"
attrib +s "Demo 6\Code"
attrib +s "Demo 6\Release"
attrib +s "Demo 6\Debug"
attrib +s "Demo 6\Images"
attrib +s +h "Demo 6\Code\desktop.ini"
attrib +s +h "Demo 6\Release\desktop.ini"
attrib +s +h "Demo 6\Debug\desktop.ini"
attrib +s +h "Demo 6\Images\desktop.ini"

attrib +s "Demo 7"
attrib +s +h "Demo 7\desktop.ini"
attrib +s "Demo 7\Code"
attrib +s "Demo 7\Release"
attrib +s "Demo 7\Debug"
attrib +s "Demo 7\Images"
attrib +s "Demo 7\Sounds"
attrib +s +h "Demo 7\Code\desktop.ini"
attrib +s +h "Demo 7\Release\desktop.ini"
attrib +s +h "Demo 7\Debug\desktop.ini"
attrib +s +h "Demo 7\Images\desktop.ini"
attrib +s +h "Demo 7\Sounds\desktop.ini"

attrib +s "Demo 8"
attrib +s +h "Demo 8\desktop.ini"
attrib +s "Demo 8\Code"
attrib +s "Demo 8\Release"
attrib +s "Demo 8\Debug"
attrib +s "Demo 8\Images"
attrib +s "Demo 8\Sounds"
attrib +s +h "Demo 8\Code\desktop.ini"
attrib +s +h "Demo 8\Release\desktop.ini"
attrib +s +h "Demo 8\Debug\desktop.ini"
attrib +s +h "Demo 8\Images\desktop.ini"
attrib +s +h "Demo 8\Sounds\desktop.ini"

attrib +s "Demo 9"
attrib +s +h "Demo 9\desktop.ini"
attrib +s "Demo 9\Code"
attrib +s "Demo 9\Release"
attrib +s "Demo 9\Debug"
attrib +s "Demo 9\Images"
attrib +s "Demo 9\Sounds"
attrib +s +h "Demo 9\Code\desktop.ini"
attrib +s +h "Demo 9\Release\desktop.ini"
attrib +s +h "Demo 9\Debug\desktop.ini"
attrib +s +h "Demo 9\Images\desktop.ini"
attrib +s +h "Demo 9\Sounds\desktop.ini"

attrib +s "Demo 10"
attrib +s +h "Demo 10\desktop.ini"
attrib +s "Demo 10\Code"
attrib +s "Demo 10\Release"
attrib +s "Demo 10\Debug"
attrib +s "Demo 10\Images"
attrib +s "Demo 10\Sounds"
attrib +s +h "Demo 10\Code\desktop.ini"
attrib +s +h "Demo 10\Release\desktop.ini"
attrib +s +h "Demo 10\Debug\desktop.ini"
attrib +s +h "Demo 10\Images\desktop.ini"
attrib +s +h "Demo 10\Sounds\desktop.ini"
